version: "3.8"
services: 
    tracer:
        build:
            context: .
            dockerfile: docker-compose.dockerfile
        environment: 
            - DD_TRACE_AGENT_URL=http://agent:8126
        depends_on: 
            - agent
    agent:
        image: datadog/agent:latest
        ports:
            - "8126:8126"
        environment: 
            - DD_API_KEY
            - DD_HOSTNAME=none
            - DD_APM_ENABLED=true
            - DD_APM_NON_LOCAL_TRAFFIC=true

